### ISSUE TITLE
No effect on iOS

### ISSUE THREAD

**Issue by p3v9d5ui** [FL3NKEY/scroll-lock#1]
This plugin is having no effect on iOS for me. I've installed the plugin and successfully called scrollLock.hide(), but on iOS there's no effect at all. 

My app is a Cordova app + Vue.js. When I run in the browser, body scrolling IS prevented, which is what I'd expect, but not on iOS.

Are you aware of any issues with running under Cordova or Vue.js?

**Comment by FL3NKEY** [comment]
Hello, can i get more information about ios version or code reference?

check if the demo works on your device:
https://fl3nkey.github.io/scroll-lock/demos/index.html

**Comment by p3v9d5ui** [comment]
Hi,

I'm on the latest iOS -- 12.0. What do you mean by code reference? An example? That's a little hard to do, because this is a Cordova project.

Yes, the demo does work, but that's running in the browser. This issue is only reproducible in the Cordova app environment. Cordova apparently uses WKWebView for iOS.

Has anyone been able to use this plugin successfully on Cordova?

**Comment by FL3NKEY** [comment]
@p3v9d5ui, plugin is updated! Try it now. (current version: 1.3.5)

https://github.com/FL3NKEY/scroll-lock/commit/bf60290d212faa0e0787c053933bb7efabf4b5ad

**Comment by p3v9d5ui** [comment]
It works now. Thanks!
