### ISSUE TITLE
Safari 10 complains about delete element.dataset.property

### ISSUE THREAD

**Issue by aariacarterweir** [FL3NKEY/scroll-lock#16]
I have submitted PR to fix: https://github.com/FL3NKEY/scroll-lock/pull/15

**Comment by FL3NKEY** [comment]
#17

**Comment by FL3NKEY** [comment]
@aariacarterweir 
Hello! It was fixed in #17 PR. If everything satisfies, close the issue please. Thanks ;)

**Comment by aariacarterweir** [comment]
Thanks man :)
