### ISSUE TITLE
[Intervention] Ignored attempt to cancel a touchmove event

### ISSUE THREAD

**Issue by raphaelportmann** [FL3NKEY/scroll-lock#19]
In some cases trying to cancel an event will fail with following error message:
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

It happens because the event is not cancelable. To fix this, check for `e.cancelable` before `e.preventDefault();` in the following two locations:
https://github.com/FL3NKEY/scroll-lock/blob/master/src/scroll-lock.js#L440
https://github.com/FL3NKEY/scroll-lock/blob/master/src/scroll-lock.js#L447
```
if(e.cancelable) {
    e.preventDefault();
}
```

![image](https://user-images.githubusercontent.com/25031352/84274884-b0ba4a00-ab30-11ea-9ba7-f995acf2be8c.png)

**Comment by Makso83** [comment]
faced this when touchmove event leaves scroll area

**Comment by FL3NKEY** [comment]
#22

https://www.npmjs.com/package/scroll-lock/v/2.1.5
