### ISSUE TITLE
many errors in console

### ISSUE THREAD

**Issue by Aleksandr-JS-Developer** [FL3NKEY/scroll-lock#21]
Found a bug while using. When (for example, a menu) is scrolled to the maximum, but the user continues to drag his finger, then a large number of errors of the form start to appear in the console:
"[Intervention] Ignored attempt to cancel a touchmove event with cancelable = false, for example because scrolling is in progress and cannot be interrupted."
The solution is very simple by adding one condition before e.PreventDefault()

`if (e.cancelable) {
   e.preventDefault();
}`

**Comment by FL3NKEY** [comment]
#22
