### ISSUE TITLE
Feature/API request

### ISSUE THREAD

**Issue by danDanV1** [FL3NKEY/scroll-lock#4]
Could you add a method, eg. AddLockableTarget() ? That way in addition to locking body, we could also lock scrollable divs.

eg. 
```
<body {{LOCKHERE}}>
   <div {{LOCKHERE}}>
      <div {{SCROLLHERE}}>

      </div>
   <div>
<body>
```

**Comment by FL3NKEY** [comment]
Sure! Feature will be added in [2.1](https://github.com/FL3NKEY/scroll-lock/pull/5)

**Comment by FL3NKEY** [comment]
#5
