### ISSUE TITLE
In scroll-enabled containers rangesliders do not work properly on touch devices

### ISSUE THREAD

**Issue by vaupeh** [FL3NKEY/scroll-lock#9]
If a scroll-enabled container contains a range-slider `<input type="range">`, this slider is hard to use on a touch-device (because of the touch-event handling?)

For an example see [this demo page](http://nuwn.de/test/scroll-lock-slider-testcase.html), that contains a regular slider and a slider in a scroll-enabled container (make sure you open it on a touch-device).

**Comment by FL3NKEY** [comment]
@vaupeh, hello!
Support for ```<input type="range">``` added in **2.1.2** #10

**Comment by vaupeh** [comment]
Works like a charm - thx!
